from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    PACKAGE_NOT_FOUND = "PACKAGE_NOT_FOUND"
    ASSESSMENT_UNAVAILABLE = "ASSESSMENT_UNAVAILABLE"
    UNAPPROVED_SOURCE = "UNAPPROVED_SOURCE"
    REGISTERED_AFTER_HALLUCINATION = "REGISTERED_AFTER_HALLUCINATION"
    REGISTERED_AFTER_ABSENCE = "REGISTERED_AFTER_ABSENCE"
    HIGH_GLOBAL_RECURRENCE = "HIGH_GLOBAL_RECURRENCE"
    ESTABLISHED_APPROVED = "ESTABLISHED_APPROVED"
    NONINTERACTIVE_REVIEW_BLOCKED = "NONINTERACTIVE_REVIEW_BLOCKED"
