CREATE OR REPLACE VIEW V_GLOBAL_RECURRENCE AS
SELECT ECOSYSTEM, REGISTRY_ORIGIN, CANONICAL_NAME,
    COUNT(DISTINCT CASE WHEN PROVENANCE = 'model_probe' THEN SOURCE_ID END)
        AS VERIFIED_MODEL_RECOMMENDATIONS,
    COUNT(DISTINCT CASE WHEN PROVENANCE = 'model_probe' THEN MODEL_CONFIGURATION_ID END)
        AS MODEL_CONFIGURATIONS,
    COUNT(DISTINCT CASE WHEN PROVENANCE = 'agent_install_attempt' THEN SOURCE_ID END)
        AS PROTECTED_AGENT_ATTEMPTS,
    COUNT(DISTINCT CASE WHEN PROVENANCE IN ('public_ci_failure', 'public_manifest')
        THEN SOURCE_ID END) AS PUBLIC_FAILED_REFERENCES,
    COUNT(DISTINCT CAST(OBSERVED_AT AS DATE)) AS OBSERVATION_DAYS,
    MAX(CASE WHEN EXPLICIT_CONTEXT THEN 1 ELSE 0 END) AS HAS_EXPLICIT_CONTEXT
FROM PACKAGE_MENTIONS
GROUP BY ECOSYSTEM, REGISTRY_ORIGIN, CANONICAL_NAME;
