CREATE OR REPLACE VIEW V_MODEL_PACKAGE_HALLUCINATION_RATE AS
SELECT M.MODEL_CONFIGURATION_ID,
    COUNT(DISTINCT M.SOURCE_ID) AS OBSERVED_RUNS,
    COUNT(DISTINCT CASE WHEN C.STATUS = 'verified_hallucination' THEN M.SOURCE_ID END)
        AS VERIFIED_HALLUCINATION_RUNS
FROM PACKAGE_MENTIONS M
LEFT JOIN CANDIDATES C ON C.ECOSYSTEM=M.ECOSYSTEM
    AND C.REGISTRY_ORIGIN=M.REGISTRY_ORIGIN AND C.CANONICAL_NAME=M.CANONICAL_NAME
WHERE M.PROVENANCE='model_probe'
GROUP BY M.MODEL_CONFIGURATION_ID;
