CREATE OR REPLACE VIEW V_REGISTRATION_TRANSITIONS AS
SELECT ECOSYSTEM, REGISTRY_ORIGIN, CANONICAL_NAME, FIRST_ABSENCE_AT, FIRST_REGISTRATION_AT
FROM CANDIDATES
WHERE STATUS = 'registered_after_absence';
