CREATE OR REPLACE VIEW V_HIGH_ATTRACTIVENESS_WATCHLIST AS
SELECT R.*, C.STATUS, C.FIRST_ABSENCE_AT
FROM V_GLOBAL_RECURRENCE R
JOIN CANDIDATES C ON C.ECOSYSTEM=R.ECOSYSTEM AND C.REGISTRY_ORIGIN=R.REGISTRY_ORIGIN
    AND C.CANONICAL_NAME=R.CANONICAL_NAME
WHERE C.STATUS IN ('verified_absent', 'verified_hallucination')
    AND (R.VERIFIED_MODEL_RECOMMENDATIONS + R.PROTECTED_AGENT_ATTEMPTS) >= 20;
