CREATE OR REPLACE VIEW V_SOURCE_POLICY_VIOLATIONS AS
SELECT ECOSYSTEM, REGISTRY_ORIGIN, CANONICAL_NAME, SOURCE_ID, OBSERVED_AT
FROM PACKAGE_MENTIONS
WHERE CONTEXT_KIND IN ('direct_url', 'vcs', 'local_path', 'alternate_registry');
