CREATE OR REPLACE VIEW V_PACKAGE_EVIDENCE_TIMELINE AS
SELECT ECOSYSTEM, REGISTRY_ORIGIN, CANONICAL_NAME, OBSERVED_AT AS EVENT_AT,
    PROVENANCE AS EVENT_KIND, SOURCE_ID AS EVENT_ID
FROM PACKAGE_MENTIONS
UNION ALL
SELECT ECOSYSTEM, REGISTRY_ORIGIN, CANONICAL_NAME, CHECKED_AT,
    STATUS, CHECK_ID
FROM REGISTRY_CHECKS
UNION ALL
SELECT ECOSYSTEM, REGISTRY_ORIGIN, CANONICAL_NAME, FIRST_SEEN_AT,
    'release', RELEASE_ID
FROM PACKAGE_RELEASES;
