CREATE OR REPLACE VIEW V_GUARD_OUTCOMES AS
SELECT D.DECISION, COUNT(*) AS DECISION_COUNT,
    SUM(CASE WHEN A.CHILD_STARTED THEN 1 ELSE 0 END) AS CHILD_START_COUNT
FROM POLICY_DECISIONS D
LEFT JOIN INSTALL_ATTEMPTS A ON A.DECISION_ID=D.DECISION_ID
GROUP BY D.DECISION;
