CREATE OR REPLACE VIEW V_RADAR_PRIVATE AS
SELECT C.ECOSYSTEM, C.REGISTRY_ORIGIN, C.CANONICAL_NAME, C.STATUS,
    C.FIRST_ABSENCE_AT, C.FIRST_REGISTRATION_AT, C.SYNTHETIC,
    COALESCE(R.VERIFIED_MODEL_RECOMMENDATIONS, 0) AS VERIFIED_MODEL_RECOMMENDATIONS,
    COALESCE(R.MODEL_CONFIGURATIONS, 0) AS MODEL_CONFIGURATIONS,
    COALESCE(R.PROTECTED_AGENT_ATTEMPTS, 0) AS PROTECTED_AGENT_ATTEMPTS,
    COALESCE(R.PUBLIC_FAILED_REFERENCES, 0) AS PUBLIC_FAILED_REFERENCES,
    COALESCE(R.OBSERVATION_DAYS, 0) AS OBSERVATION_DAYS,
    COALESCE(R.HAS_EXPLICIT_CONTEXT, 0) AS HAS_EXPLICIT_CONTEXT
FROM CANDIDATES C
LEFT JOIN V_GLOBAL_RECURRENCE R ON R.ECOSYSTEM=C.ECOSYSTEM
    AND R.REGISTRY_ORIGIN=C.REGISTRY_ORIGIN AND R.CANONICAL_NAME=C.CANONICAL_NAME;
