CREATE OR REPLACE VIEW V_RADAR_PUBLIC_AGGREGATES AS
SELECT ECOSYSTEM, STATUS, COUNT(*) AS PACKAGE_COUNT,
    SUM(CASE WHEN SYNTHETIC THEN 1 ELSE 0 END) AS SYNTHETIC_PACKAGE_COUNT
FROM CANDIDATES
GROUP BY ECOSYSTEM, STATUS;
