CREATE TABLE REGISTRY_BASELINES (
    BASELINE_ID VARCHAR(100) PRIMARY KEY, ECOSYSTEM VARCHAR(20) NOT NULL,
    SOURCE_URL VARCHAR(2000) NOT NULL, SOURCE_CURSOR VARCHAR(200), CAPTURED_AT TIMESTAMP NOT NULL,
    PROJECT_COUNT DECIMAL(18,0) NOT NULL, CONTENT_SHA256 VARCHAR(64) NOT NULL,
    NORMALIZATION_VERSION VARCHAR(50) NOT NULL
);
CREATE TABLE MODEL_CONFIGURATIONS (
    CONFIGURATION_ID VARCHAR(100) PRIMARY KEY, PROVIDER VARCHAR(100) NOT NULL,
    MODEL_ID VARCHAR(200) NOT NULL, PARAMETERS_JSON VARCHAR(2000000) NOT NULL,
    FIRST_SEEN_AT TIMESTAMP NOT NULL, LAST_SEEN_AT TIMESTAMP NOT NULL
);
CREATE TABLE PROMPT_TASKS (
    PROMPT_TASK_ID VARCHAR(100) PRIMARY KEY, SUITE_VERSION VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL, PROMPT_SHA256 VARCHAR(64) NOT NULL,
    EXPECTED_ECOSYSTEM VARCHAR(20) NOT NULL
);
CREATE TABLE MODEL_RUNS (
    RUN_ID VARCHAR(100) PRIMARY KEY, CONFIGURATION_ID VARCHAR(100) NOT NULL,
    PROMPT_TASK_ID VARCHAR(100) NOT NULL, RUN_AT TIMESTAMP NOT NULL,
    RESPONSE_SHA256 VARCHAR(64) NOT NULL, STATUS VARCHAR(50) NOT NULL
);
CREATE TABLE PACKAGE_MENTIONS (
    MENTION_ID VARCHAR(100), ECOSYSTEM VARCHAR(20) NOT NULL,
    REGISTRY_ORIGIN VARCHAR(2000) NOT NULL, CANONICAL_NAME VARCHAR(300) NOT NULL,
    PROVENANCE VARCHAR(50) NOT NULL, SOURCE_ID VARCHAR(200) NOT NULL,
    MODEL_CONFIGURATION_ID VARCHAR(100), OBSERVED_AT TIMESTAMP NOT NULL,
    CONTEXT_KIND VARCHAR(50), CONFIDENCE DECIMAL(5,4), EXPLICIT_CONTEXT BOOLEAN NOT NULL
);
CREATE TABLE REGISTRY_CHECKS (
    CHECK_ID VARCHAR(100) PRIMARY KEY, ECOSYSTEM VARCHAR(20) NOT NULL,
    REGISTRY_ORIGIN VARCHAR(2000) NOT NULL, CANONICAL_NAME VARCHAR(300) NOT NULL,
    ENDPOINT VARCHAR(2000) NOT NULL, STATUS VARCHAR(50) NOT NULL,
    HTTP_STATUS DECIMAL(5,0), CHECKED_AT TIMESTAMP NOT NULL,
    RESPONSE_SHA256 VARCHAR(64), ERROR_CLASS VARCHAR(100)
);
CREATE TABLE CANDIDATES (
    ECOSYSTEM VARCHAR(20) NOT NULL, REGISTRY_ORIGIN VARCHAR(2000) NOT NULL,
    CANONICAL_NAME VARCHAR(300) NOT NULL, STATUS VARCHAR(50) NOT NULL,
    FIRST_ABSENCE_AT TIMESTAMP, FIRST_REGISTRATION_AT TIMESTAMP,
    DISCLOSURE_CLASS VARCHAR(100) NOT NULL, SYNTHETIC BOOLEAN NOT NULL
);
CREATE TABLE PUBLIC_SOURCE_OBSERVATIONS (
    OBSERVATION_ID VARCHAR(100) PRIMARY KEY, ECOSYSTEM VARCHAR(20) NOT NULL,
    REGISTRY_ORIGIN VARCHAR(2000) NOT NULL, CANONICAL_NAME VARCHAR(300) NOT NULL,
    PUBLIC_URL_SHA256 VARCHAR(64) NOT NULL, SOURCE_KIND VARCHAR(50) NOT NULL,
    REMOVAL_STATE VARCHAR(50), OBSERVED_AT TIMESTAMP NOT NULL
);
CREATE TABLE CLIENT_INSTALL_OBSERVATIONS (
    OBSERVATION_ID VARCHAR(100) PRIMARY KEY, ECOSYSTEM VARCHAR(20) NOT NULL,
    REGISTRY_ORIGIN VARCHAR(2000) NOT NULL, CANONICAL_NAME VARCHAR(300) NOT NULL,
    CLIENT_PSEUDONYM VARCHAR(100) NOT NULL, AGENT_FAMILY VARCHAR(100) NOT NULL,
    REQUESTED_SOURCE VARCHAR(50) NOT NULL, OBSERVED_AT TIMESTAMP NOT NULL
);
CREATE TABLE PACKAGE_RELEASES (
    RELEASE_ID VARCHAR(100) PRIMARY KEY, ECOSYSTEM VARCHAR(20) NOT NULL,
    REGISTRY_ORIGIN VARCHAR(2000) NOT NULL, CANONICAL_NAME VARCHAR(300) NOT NULL,
    VERSION VARCHAR(200) NOT NULL, UPLOADED_AT TIMESTAMP, FIRST_SEEN_AT TIMESTAMP NOT NULL,
    ARTIFACT_SHA256 VARCHAR(64)
);
CREATE TABLE STATIC_FINDINGS (
    FINDING_ID VARCHAR(100) PRIMARY KEY, ARTIFACT_SHA256 VARCHAR(64) NOT NULL,
    RULE_ID VARCHAR(100) NOT NULL, SEVERITY VARCHAR(20) NOT NULL,
    FILE_PATH_HASH VARCHAR(64), BOUNDED_EVIDENCE VARCHAR(2000)
);
CREATE TABLE POLICY_RULES (
    POLICY_VERSION VARCHAR(100) NOT NULL, RULE_ID VARCHAR(100) NOT NULL,
    EFFECTIVE_AT TIMESTAMP NOT NULL, RULE_JSON VARCHAR(2000000) NOT NULL
);
CREATE TABLE POLICY_DECISIONS (
    DECISION_ID VARCHAR(100) PRIMARY KEY, REQUEST_ID VARCHAR(100) NOT NULL,
    ECOSYSTEM VARCHAR(20) NOT NULL, REGISTRY_ORIGIN VARCHAR(2000) NOT NULL,
    CANONICAL_NAME VARCHAR(300) NOT NULL, ABSENCE_CONFIDENCE DECIMAL(3,0),
    TARGET_ATTRACTIVENESS DECIMAL(3,0) NOT NULL, PACKAGE_POLICY_RISK DECIMAL(3,0) NOT NULL,
    DECISION VARCHAR(20) NOT NULL, REASON_CODES_JSON VARCHAR(2000) NOT NULL,
    POLICY_VERSION VARCHAR(100) NOT NULL, DECIDED_AT TIMESTAMP NOT NULL
);
CREATE TABLE INSTALL_ATTEMPTS (
    ATTEMPT_ID VARCHAR(100) PRIMARY KEY, DECISION_ID VARCHAR(100) NOT NULL,
    COMMAND_SHA256 VARCHAR(64) NOT NULL, AGENT_FAMILY VARCHAR(100) NOT NULL,
    PROJECT_PSEUDONYM VARCHAR(100) NOT NULL, DECISION VARCHAR(20) NOT NULL,
    CHILD_STARTED BOOLEAN NOT NULL, ATTEMPTED_AT TIMESTAMP NOT NULL
);
CREATE TABLE APPROVAL_GRANTS (
    APPROVAL_ID VARCHAR(100) PRIMARY KEY, SCOPE_JSON VARCHAR(2000000) NOT NULL,
    SIGNER VARCHAR(200) NOT NULL, CREATED_AT TIMESTAMP NOT NULL, EXPIRES_AT TIMESTAMP NOT NULL,
    CONSUMED_AT TIMESTAMP, NONCE VARCHAR(200) NOT NULL
);
CREATE TABLE EVIDENCE_ATTESTATIONS (
    ATTESTATION_ID VARCHAR(100) PRIMARY KEY, DECISION_ID VARCHAR(100) NOT NULL,
    CANONICAL_JSON_SHA256 VARCHAR(64) NOT NULL, PREVIOUS_SHA256 VARCHAR(64),
    CREATED_AT TIMESTAMP NOT NULL
);
CREATE TABLE JOB_CURSORS (
    JOB_NAME VARCHAR(100) NOT NULL, SOURCE_ID VARCHAR(200) NOT NULL,
    CURSOR_VALUE VARCHAR(2000), UPDATED_AT TIMESTAMP NOT NULL
);
