-- Durable Guard state. Exasol maintains indexes automatically; primary keys and
-- unique constraints declare the access paths and integrity requirements here.
ALTER TABLE POLICY_DECISIONS ADD COLUMN REQUEST_JSON VARCHAR(2000000);
ALTER TABLE POLICY_DECISIONS ADD COLUMN EVIDENCE_AS_OF TIMESTAMP;
ALTER TABLE POLICY_DECISIONS ADD COLUMN EVIDENCE_ATTESTATION VARCHAR(64);

ALTER TABLE INSTALL_ATTEMPTS ADD COLUMN MANAGER VARCHAR(32);
ALTER TABLE INSTALL_ATTEMPTS ADD COLUMN ARGUMENTS_JSON VARCHAR(2000000);
ALTER TABLE INSTALL_ATTEMPTS ADD COLUMN IDEMPOTENCY_KEY VARCHAR(256);

ALTER TABLE APPROVAL_GRANTS ADD COLUMN REQUEST_ID VARCHAR(100);
ALTER TABLE APPROVAL_GRANTS ADD COLUMN INTERVENTION_ID VARCHAR(100);
ALTER TABLE APPROVAL_GRANTS ADD COLUMN CONSUMED_REQUEST_ID VARCHAR(100);
ALTER TABLE APPROVAL_GRANTS ADD COLUMN CONSUMPTION_METADATA_JSON VARCHAR(2000000);

CREATE TABLE INTERVENTIONS (
    INTERVENTION_ID VARCHAR(100) PRIMARY KEY,
    DECISION_ID VARCHAR(100) NOT NULL,
    REQUEST_JSON VARCHAR(2000000) NOT NULL,
    DECISION_JSON VARCHAR(2000000) NOT NULL,
    EVIDENCE_LABELS_JSON VARCHAR(2000000) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    APPROVAL_ID VARCHAR(100),
    RESOLVED_AT TIMESTAMP
);

CREATE TABLE IDEMPOTENCY_CLAIMS (
    IDEMPOTENCY_KEY VARCHAR(256) PRIMARY KEY,
    REQUEST_HASH VARCHAR(64) NOT NULL,
    RESPONSE_REFERENCE VARCHAR(200) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE EVENT_LOG (
    EVENT_ID DECIMAL(18,0) IDENTITY,
    EVENT_KEY VARCHAR(64) PRIMARY KEY,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    PAYLOAD_JSON VARCHAR(2000000) NOT NULL,
    OCCURRED_AT TIMESTAMP NOT NULL
);

CREATE TABLE WORKER_JOBS (
    JOB_NAME VARCHAR(100) PRIMARY KEY,
    SOURCE_ID VARCHAR(200) NOT NULL,
    CURSOR_VALUE VARCHAR(2000),
    OUTCOME VARCHAR(100),
    DATA_AS_OF TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE WORKER_LEASES (
    JOB_NAME VARCHAR(100) PRIMARY KEY,
    LEASE_OWNER VARCHAR(200) NOT NULL,
    ACQUIRED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL
);

CREATE TABLE CREDENTIAL_AUDIT (
    AUDIT_ID VARCHAR(100) PRIMARY KEY,
    CREDENTIAL_ID VARCHAR(200) NOT NULL,
    ACTION_TYPE VARCHAR(100) NOT NULL,
    REQUEST_ID VARCHAR(100),
    OCCURRED_AT TIMESTAMP NOT NULL,
    METADATA_JSON VARCHAR(2000000) NOT NULL
);
